[phases.setup]
nixPkgs = ['python310', 'ffmpeg', 'imagemagick']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.start]
cmd = 'python caption_backend/app.py'
 
